/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_TestJNI */

#ifndef _Included_test_TestJNI
#define _Included_test_TestJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_alone_in_deepspace_Main_init(JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
